"use client";

import { Shield, CheckCircle2 } from "lucide-react";
import { DemoStepIndicator } from "@/components/DemoStepIndicator";
import { DemoCallout } from "@/components/DemoCallout";
import { reportData, candidateFormFields } from "@/lib/demoData";

export default function ReportReadyPage() {
  return (
    <>
      <DemoStepIndicator currentSlug="report-ready" />
      <div style={{ background: "#F5F5F0", minHeight: "100vh", padding: "1.5rem 1rem 3rem" }}>
        <div className="report-container">
          <DemoCallout items={[
            { title: "Final Report", text: "This is the comprehensive background verification report generated by the admin. It mirrors the PDF that gets downloaded and emailed to the company.", arrow: "down" },
            { title: "Service Results", text: "Each verification service has its own section showing the candidate's answers, the verifier's findings, and the final status.", arrow: "down" },
            { title: "Audit Trail", text: "Every verification attempt is logged with the verifier's name, respondent details, timestamps, and comments for full traceability.", arrow: "down" },
          ]} />
          {/* Report Header */}
          <div className="report-header">
            <div className="report-header-top">
              <div>
                <h2>🛡️ Cluso Background Verification Report</h2>
                <p className="report-number">Report No: {reportData.reportNumber}</p>
              </div>
              <span className="status-pill status-pill-verified" style={{ fontSize: "0.88rem", padding: "0.35rem 0.8rem" }}>
                ✅ Verified
              </span>
            </div>
            <div className="report-info-grid">
              <div className="report-info-item">
                <label>Candidate</label>
                <span>{reportData.candidate.name}</span>
              </div>
              <div className="report-info-item">
                <label>Company</label>
                <span>{reportData.company.name}</span>
              </div>
              <div className="report-info-item">
                <label>Generated On</label>
                <span>{new Date(reportData.generatedAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</span>
              </div>
              <div className="report-info-item">
                <label>Generated By</label>
                <span>{reportData.generatedByName}</span>
              </div>
              <div className="report-info-item">
                <label>Candidate Email</label>
                <span>{reportData.candidate.email}</span>
              </div>
              <div className="report-info-item">
                <label>Verified By</label>
                <span>{reportData.verifiedByName}</span>
              </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="report-body">
            {/* Personal Details */}
            <div className="report-section">
              <div className="report-section-header">
                <h3 className="report-section-title">👤 Personal Details</h3>
              </div>
              <div className="report-section-body">
                {reportData.personalDetails.map((field, i) => (
                  <div key={i} className="report-field">
                    <span className="report-field-label">{field.question}</span>
                    <span className="report-field-value">{field.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Service Verifications */}
            {reportData.services.map((service) => (
              <div key={service.serviceId} className="report-section">
                <div className="report-section-header">
                  <h3 className="report-section-title">📋 {service.serviceName}</h3>
                  <span className="status-pill status-pill-verified" style={{ display: "flex", alignItems: "center", gap: "0.3rem" }}>
                    <CheckCircle2 size={13} /> {service.status}
                  </span>
                </div>
                <div className="report-section-body">
                  {/* Candidate Answers */}
                  {service.candidateAnswers.map((answer, i) => (
                    <div key={i} className="report-field">
                      <span className="report-field-label">{answer.question}</span>
                      <span className="report-field-value">{answer.value}</span>
                    </div>
                  ))}

                  {/* Verification Attempts */}
                  {service.attempts.map((attempt, i) => (
                    <div key={i} className="report-attempt">
                      <div className="report-attempt-header">
                        <strong style={{ fontSize: "0.88rem", color: "#334155" }}>Verification Attempt</strong>
                        <span className="status-pill status-pill-verified" style={{ fontSize: "0.72rem" }}>
                          {attempt.status}
                        </span>
                      </div>
                      <div style={{ display: "grid", gap: "0.3rem", fontSize: "0.84rem", color: "#4b5563" }}>
                        <div><strong>Verifier:</strong> {attempt.verifierName}</div>
                        <div><strong>Mode:</strong> {attempt.verificationMode}</div>
                        <div><strong>Date:</strong> {new Date(attempt.attemptedAt).toLocaleString("en-IN")}</div>
                        <div><strong>Respondent:</strong> {attempt.respondentName} ({attempt.respondentEmail})</div>
                        <div><strong>Comment:</strong> {attempt.comment}</div>
                        {attempt.respondentComment && (
                          <div style={{ fontStyle: "italic", borderLeft: "3px solid #86efac", paddingLeft: "0.6rem", marginTop: "0.3rem" }}>
                            &quot;{attempt.respondentComment}&quot;
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}

            {/* Disclaimer */}
            <div style={{ background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "12px", padding: "1.2rem", fontSize: "0.75rem", color: "#64748b", lineHeight: 1.6, marginTop: "1.5rem" }}>
              <div style={{ textAlign: "center", fontWeight: "700", color: "#475569", marginBottom: "0.8rem", letterSpacing: "0.05em" }}>--END OF REPORT--</div>
              <div style={{ fontWeight: "700", color: "#475569", marginBottom: "0.5rem" }}>IMPORTANT NOTICE & DISCLAIMER</div>
              <p style={{ margin: "0 0 0.75rem" }}>
                This report is provided by CLUSO INFOLINK PRIVATE LIMITED on a strictly confidential basis, solely for the exclusive use of the recipient for legitimate corporate and business purposes. It may not be reproduced, redistributed, or disclosed, in whole or in part, in any manner whatsoever without prior written consent.
              </p>
              <p style={{ margin: "0 0 0.75rem" }}>
                While CLUSO INFOLINK PRIVATE LIMITED endeavors to ensure the highest level of accuracy and diligence in procuring, collecting, and compiling this data, it does not warrant or guarantee the absolute completeness, correctness, or timeliness of the information contained herein. Consequently, CLUSO INFOLINK PRIVATE LIMITED shall not be held liable for any direct, indirect, or consequential loss, damage, or injury resulting from any errors, omissions, or negligence in the procurement or communication of this information. Reliance upon this report is strictly at the user's sole risk.
              </p>
              <p style={{ margin: 0 }}>
                The recipient acknowledges that the handling and utilization of this data must strictly align with all prevailing Indian regulatory frameworks, including but not limited to the Digital Personal Data Protection Act, 2023 (DPDP Act) and the Information Technology Act, 2000, along with all subsequent amendments and rules.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
